### ISSUE TITLE
Trie sur le tableau des factures

### ISSUE THREAD

**Issue by adri1s** [pg3io/dashboard3#1]

**Comment by Poloriba** [comment]
Add the Alpha sort, and make a <b-table> div for dynamique table.

fb978279c9a21f5311e93b2db6f804c45cd519fc

**Comment by Poloriba** [comment]
Finish sorting tab, add sort by date.

2d19c3ab0051728444cbd091f52df5277fb7f71c

**Comment by Poloriba** [comment]
auto sort date

ba1b352d42089db4f343642485a05782c1f21674
