### ISSUE TITLE
Modification du lecteur de PDF

### ISSUE THREAD

**Issue by adri1s** [pg3io/dashboard3#2]
Load un vrai lecteur de PDF pour l'aperçu des factures. Lectures avec les boutons d'impression et enregistrement intégré.
(retirer les boutons inutiles)

**Comment by Poloriba** [comment]
ON DEV BRANCH 

 {~} Modifie the pdf reader with <embed> div - close #2 {~} 

7a9ffa1cade8ef92ded0d3ce61f11b4b4d721b7a

**Comment by adri1s** [comment]
Pour infi @Poloriba , Il fallait ajouter dans strapi les origin autorisés
Doc strapi > xframe => https://strapi.io/documentation/developer-docs/latest/setup-deployment-guides/configurations.html#security-middlewares

Exemple

```
module.exports = {
  load : {
     ...
  }
  settings: {
    cors: {
      origin: ['https://...','https://...'],
    },
    xframe: {
      value: 'ALLOW-FROM',
    }
  },
};
```
