### ISSUE TITLE
Cypress

### ISSUE THREAD

**Issue by adri1s** [pg3io/dashboard3#22]
Faire un jeu de teste [Cypress](https://www.cypress.io/) de l'applicatif

**Comment by gummyWalrus** [comment]
Les commits [6dc6506](https://github.com/pg3io/dashboard3/commit/6dc65061bfd1161154019b9d13e1c737d5e0611f), [e9bb1fb](https://github.com/pg3io/dashboard3/commit/e9bb1fbc1fad6155b428214cc7cd13c312e1ca1f) et [264d9e96](https://github.com/pg3io/dashboard3/commit/264d9e96eb8c66a594abc7eb1348aa7ef6ce0726) constituent une première version des jeux de tests

**Comment by gummyWalrus** [comment]
Le jeu de test à été complété et sera maintenu à jour au fur et à mesure des nouvelles features
