### ISSUE TITLE
Changement de mot de passe et mot de passe oublié ne fonctionnent plus

### ISSUE THREAD

**Issue by adri1s** [pg3io/dashboard3#26]
Les fonctions ci-dessous ne fonctionnent plus :
* Changement de mot de passe : dans le menu profile
* Mot de passe oublié : sur la page login

**Comment by gummyWalrus** [comment]
Changement de mot de passe /profile patché par le commit [9e92a](https://github.com/pg3io/dashboard3/commit/9e92a8336b1eb4119259be965d58afdff5a3c4d7)

**Comment by gummyWalrus** [comment]
Changement de mot de passe par mail fonctionel, aucune modification à spécifier.
