### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by adri1s** [pg3io/dashboard3#29]
Mise en place d'un Dark mode
* Bouton d'activation dans les paramètres
* Prise en compte du mode du système

**Comment by gummyWalrus** [comment]
Issue résolue par le commit [674aee](https://github.com/pg3io/dashboard3/commit/674aeed8aceda0aa178ec0163c03639392195d69)

Le site analyse la regle media "darkMode" fournie par l'OS et choisi le thème, le cas échéant (parametre vide ou faux)
Un switch accessible sur la home permet de passer en dark mode et  met un cookie à l'utilisateur via localStorage pour rappeler sa préférence

**Comment by adri1s** [comment]
Sur la preprod quand je suis en dark mode (forcé par le theme de l'OS) je ne peux pas passer en mode normal.

**Comment by adri1s** [comment]
Le texte dans le fond des champs de login sont en bleu (white) et violet (dark) les laisser en gris sur les 2 modes. Je pense que c'est en relation avec la couleur des liens hypertexte

**Comment by gummyWalrus** [comment]
Issue résolue par le commit [c87f2](https://github.com/pg3io/dashboard3/commit/c87f248473dd0f9fc019e2ed52e8e81e8c1e5a7d)
Couleur primary modifiée dans le dark.css,
Retirer modif de couleur sur les placeholders
Le cookie de dark mode défini en priorité le thème à utiliser
