### ISSUE TITLE
bug bouton fenêtre ticket

### ISSUE THREAD

**Issue by adri1s** [pg3io/dashboard3#35]
Quelle est la différence entre "Cancel" et "OK" ? et la base nous les avions pas retiré ces boutons ?
Donc on vire Cancel et OK et à la place on met "Détails"

![Capture d’écran du 2021-10-10 21-51-59](https://user-images.githubusercontent.com/896312/136711047-1a11b6c1-f426-4f71-a5d6-ab407ebf8828.png)

**Comment by gummyWalrus** [comment]
Il ya du y'avoir un conflit après un merge. Je m'en occupe !
