### ISSUE TITLE
add gravatar

### ISSUE THREAD

**Issue by adri1s** [pg3io/dashboard3#7]
Générer le cas au une personne a une photo sur gravatar => https://www.npmjs.com/package/vue-gravatar

**Comment by Poloriba** [comment]
- Add gravatar Vuejs component.
- Modifie profile section with profile picture of gravatar.
- add href 'https://fr.gravatar.com/' on profile section.
- add profile picture in navbar.

7239dd58e8be313cd0f8aa4b63b76146468720f0
